# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{plastic}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Randy Reddig", "Cameron Walters", "Chris Kampmeier", "Erica Kwan", "Matthew O'Connor", "Damon McCormick", "Brian Jenkins"]
  s.date = %q{2010-09-01}
  s.description = %q{Handle credit, debit, bank and other cards.}
  s.email = %q{github@squareup.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "HISTORY.rdoc",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "lib/plastic.rb",
     "lib/plastic/core.rb",
     "lib/plastic/duck_type.rb",
     "lib/plastic/track.rb",
     "lib/plastic/validations.rb",
     "lib/plastic/version.rb",
     "plastic.gemspec",
     "spec/plastic/core_spec.rb",
     "spec/plastic/duck_type_spec.rb",
     "spec/plastic/track_spec.rb",
     "spec/plastic/validations_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/square/plastic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Credit card library for Ruby.}
  s.test_files = [
    "spec/plastic/core_spec.rb",
     "spec/plastic/duck_type_spec.rb",
     "spec/plastic/track_spec.rb",
     "spec/plastic/validations_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

